
purpose_identifier_task:
  description: >
    To read and understand the user input prompt {QUERY_TEXT}. The user will either ask to 1) Upload a document OR 2) Retrieve information OR 3) Upload document and retrieve information.
    To select one of the following outputs 1) Upload a document OR 2) Retrieve information OR 3) Upload document and retrieve information. Do not give anything else in your response other than one of the above words
  expected_output: >
    One of the follwing outputs from 1) Upload OR 2) Retrieve OR 3) Upload and Retrieve. Output should contain only these words, no other verbose response.
  agent: purpose_identifier_agent
